language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
install: npm install
before_script: npm run dist
script: npm test
before_deploy: "echo 'Passed all unit tests; Preparing to deploy Staff Picks App to AWS'"
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: $AWS_PRODUCTION_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_PRODUCTION_ACCESS_SECRET
  region: us-east-1
  app: nypl-staff-picks-app
  env: staff-picks-travis
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: nypl-staff-picks-app
  on:
    repo: NYPL/staff-picks
    branch: setup-travis-ci-aws
after_deploy: "echo 'Successfully executed deploy for Staff Picks App on AWS'"
