language: node_js
node_js:
- '6.14.4'
cache:
  directories:
  - node_modules
install: npm install
before_script: npm run dist
script: npm test
before_deploy: echo 'All unit tests passed; Successfull built distribution assets;
  Preparing to deploy Staff Picks to AWS.'
# For every branch mentioned below that does not match the current branch, the following
# message will appear:
#   "Skipping a deployment with the elasticbeanstalk provider because this branch is not permitted"
# When a Pull Request is submitted and Travis finishes building, the following message will appear:
#   "Skipping a deployment with the elasticbeanstalk provider because the current build is a pull request."
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: nypl-staff-picks-app
  env: staff-picks-production
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: staff-picks-production
  on:
    repo: NYPL/staff-picks
    branch: master
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: nypl-staff-picks-app
  env: staff-picks-qa
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: staff-picks-qa
  on:
    repo: NYPL/staff-picks
    branch: qa
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  region: us-east-1
  app: nypl-staff-picks-app
  env: staff-picks-development
  bucket_name: elasticbeanstalk-us-east-1-224280085904
  bucket_path: staff-picks-development
  on:
    repo: NYPL/staff-picks
    branch: development
after_deploy: echo 'Successfully executed deploy trigger for Staff Picks on AWS'
env:
  global:
    secure: Jtyj6LV2p3nClM1sFjBo2/lNCJzTLwcgxTbEO0lqHaoEaq3Z8xb6r18w6MqOk2Sj4vUJMRTaqAUSFunqlbNk/XRDOROnNpovA/ix00RMLs5p2Hxewza1oC5CxnaCfDCCmPqSCplpe9kZWR7HqBvAuKD/ErBlV+uvjBAxtfLn+WNWZns385tLjDD/i85sm1Oc6T7CMHePKz9HsFUPmhwt2KYEGoftSiSrckPTEiUShQj8YgcqaUNraJyW1pPAJ0fc7Q/XI7AQ61aO2zm9yf8rhCJxmreAaf/wej5bQHZObU6IK4eGmLazMknO+Er5u2MmbEBA9wmGvDjcWjzyBQbNFdFUO+OQVrHwwtPUoXlkRm5L0IeTtQmJG3kI1yIy3fgk0aQsQVhfSGmGZUjbusq7PDRiBD6H5+LfVjL1T+RUZJz6C8LDMSV+gYRF4xD285gc5I+C8nQ5EGddUVNeq3Sk7W3DAc+8zNdKHCi20BcKwY+4e93y41mT2Lv6nRg0+4gFDQltH50hpo8kwBH9jIR3ZAQqQ023EgMWzQNx7P58rxrLxU/u9ZxJl768satFtAmL1quPD7mBpDN0FTZu+ne9hdXairQWbMoRgPKTKlbdf0LoAFJksbrGKhGlX0CwEYYlRiY6MXcVVvmv14mcNn1CM4+uoy7P/9cEGxKQm2OeBEY=
